// automatically generated by the FlatBuffers compiler, do not modify

package org.enso.languageserver.protocol;

public final class InboundPayload {
  private InboundPayload() { }
  public static final byte NONE = 0;
  public static final byte SessionInit = 1;

  public static final String[] names = { "NONE", "SessionInit", };

  public static String name(int e) { return names[e]; }
}

