// automatically generated by the FlatBuffers compiler, do not modify

package org.enso.languageserver.protocol;

public final class OutboundPayload {
  private OutboundPayload() { }
  public static final byte NONE = 0;
  public static final byte SessionInitResponse = 1;
  public static final byte VisualisationUpdate = 2;

  public static final String[] names = { "NONE", "SessionInitResponse", "VisualisationUpdate", };

  public static String name(int e) { return names[e]; }
}

