# https://aka.ms/yaml

trigger:
  branches:
    include: [ "*" ]
  paths:
    exclude:
      - .github/*
      - doc/*
      - .gitignore
      - .scalafmt.conf
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md

pr: none

variables:
  graalVersion: 19.3.0 # Please ensure this is in sync with the graalAPIVersion in build.sbt
  graalReleasesUrl: https://github.com/graalvm/graalvm-ce-builds/releases/download
  graalDistributionName: graalvm-ce-java8
  sbtVersion: 1.3.3    # Please ensure this is in sync with project/build.properties
  wasmpackVersion: 0.8.1
  rustToolchain: nightly-2019-12-13

jobs:
  - job: Linux
    timeoutInMinutes: 90
    pool:
      vmImage: 'Ubuntu-16.04'
    container:
      image: oracle/graalvm-ce:$(graalVersion)-java8
      options: "--name ci-container -v /usr/bin/docker:/tmp/docker:ro"
    steps:
      - script: pwd
      - script: echo parser-js/nightly/$(Build.SourceVersion)
      - script: |
          echo bar > foo.txt
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Pipeline.Workspace)/s/foo.txt'
          artifact: 'parser-js'
          publishLocation: 'pipeline'
