// automatically generated by the FlatBuffers compiler, do not modify

package org.enso.languageserver.protocol.executioncontext;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class VisualisationContext extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static VisualisationContext getRootAsVisualisationContext(ByteBuffer _bb) { return getRootAsVisualisationContext(_bb, new VisualisationContext()); }
  public static VisualisationContext getRootAsVisualisationContext(ByteBuffer _bb, VisualisationContext obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VisualisationContext __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public org.enso.languageserver.protocol.util.UUID visualisationId() { return visualisationId(new org.enso.languageserver.protocol.util.UUID()); }
  public org.enso.languageserver.protocol.util.UUID visualisationId(org.enso.languageserver.protocol.util.UUID obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public org.enso.languageserver.protocol.util.UUID contextId() { return contextId(new org.enso.languageserver.protocol.util.UUID()); }
  public org.enso.languageserver.protocol.util.UUID contextId(org.enso.languageserver.protocol.util.UUID obj) { int o = __offset(6); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }
  public org.enso.languageserver.protocol.util.UUID expressionId() { return expressionId(new org.enso.languageserver.protocol.util.UUID()); }
  public org.enso.languageserver.protocol.util.UUID expressionId(org.enso.languageserver.protocol.util.UUID obj) { int o = __offset(8); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startVisualisationContext(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addVisualisationId(FlatBufferBuilder builder, int visualisationIdOffset) { builder.addStruct(0, visualisationIdOffset, 0); }
  public static void addContextId(FlatBufferBuilder builder, int contextIdOffset) { builder.addStruct(1, contextIdOffset, 0); }
  public static void addExpressionId(FlatBufferBuilder builder, int expressionIdOffset) { builder.addStruct(2, expressionIdOffset, 0); }
  public static int endVisualisationContext(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VisualisationContext get(int j) { return get(new VisualisationContext(), j); }
    public VisualisationContext get(VisualisationContext obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

