// automatically generated by the FlatBuffers compiler, do not modify

package org.enso.languageserver.protocol.session;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class SessionInit extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_1_12_0(); }
  public static SessionInit getRootAsSessionInit(ByteBuffer _bb) { return getRootAsSessionInit(_bb, new SessionInit()); }
  public static SessionInit getRootAsSessionInit(ByteBuffer _bb, SessionInit obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public SessionInit __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public org.enso.languageserver.protocol.util.EnsoUUID identifier() { return identifier(new org.enso.languageserver.protocol.util.EnsoUUID()); }
  public org.enso.languageserver.protocol.util.EnsoUUID identifier(org.enso.languageserver.protocol.util.EnsoUUID obj) { int o = __offset(4); return o != 0 ? obj.__assign(o + bb_pos, bb) : null; }

  public static void startSessionInit(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addIdentifier(FlatBufferBuilder builder, int identifierOffset) { builder.addStruct(0, identifierOffset, 0); }
  public static int endSessionInit(FlatBufferBuilder builder) {
    int o = builder.endTable();
    builder.required(o, 4);  // identifier
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public SessionInit get(int j) { return get(new SessionInit(), j); }
    public SessionInit get(SessionInit obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

