// automatically generated by the FlatBuffers compiler, do not modify

package org.enso.languageserver.protocol.util;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class UUID extends Struct {
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public UUID __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long leastSigBits() { return bb.getLong(bb_pos + 0); }
  public long mostSigBits() { return bb.getLong(bb_pos + 8); }

  public static int createUUID(FlatBufferBuilder builder, long leastSigBits, long mostSigBits) {
    builder.prep(8, 16);
    builder.putLong(mostSigBits);
    builder.putLong(leastSigBits);
    return builder.offset();
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public UUID get(int j) { return get(new UUID(), j); }
    public UUID get(UUID obj, int j) {  return obj.__assign(__element(j), bb); }
  }
}

