name: Parser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

env:
  wasmpackVersion: 0.8.1

strategy:
  matrix:
    os: [macOS-latest, ubuntu-latest, windows-latest]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Parser Sources
        uses: actions/checkout@v2

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Parser Sources
        uses: actions/checkout@v2
