name: Parser CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "*" ]

env:
  wasmpackVersion: 0.8.1

jobs:
  test:
    name: Test Parser
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Parser Sources
        uses: actions/checkout@v2

  build:
    name: Build Parser
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Checkout Parser Sources
        uses: actions/checkout@v2
