name: Enso CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - .github/*
      - doc/*
      - .gitignore
      - .scalafmt.conf
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md

env:
  # Please ensure that this is in sync with graalAPIVersion in build.sbt
  graalVersion: 20.0.0
  javaVersion: java8
  # Please ensure that this is in sync with project/build.properties
  sbtVersion: 1.3.3

jobs:

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      matrix:
#         os: [windows-latest, macOS-latest, ubuntu-latest]
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        path: enso
    - name: Setup GraalVM Environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: ${{ env.graalVersion }}.${{ env.javaVersion }}
    - name: Set Up SBT
      run: |
        curl -fSL -o sbt.tgz https://piccolo.link/sbt-${{env.sbtVersion}}.tgz
        tar -xzf sbt.tgz
        echo ::add-path::$GITHUB_WORKSPACE/sbt/bin/ 
    - name: CD to Code Directory
      run: cd ./enso/
    - name: Test Enso
      run: sbt -no-colors test
#     - name: Benchmark the Parser
#       run: sbt -no-colors syntax/bench
#     - name: Check Runtime Benchmark Compilation
#       run: sbt -no-colors runtime/Benchmark/compile
#     - name: Build the Uberjar
#       run: sbt -no-colors runner/assembly
#     - name: Test the Uberjar
#       run: ./enso.jar --run ci/Test.enso
      

  build: 
    name: Build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
