name: Enso CI (MacOS, Linux, Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths-ignore: 
      - .github/*
      - doc/*
      - .gitignore
      - .scalafmt.conf
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - LICENSE
      - README.md

env:
  # Please ensure that this is in sync with graalAPIVersion in build.sbt
  graalVersion: 20.0.0.java8
  javaVersion: java8
  # Please ensure that this is in sync with project/build.properties
  sbtVersion: 1.3.3

jobs:
  build:
    name: Enso CI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - name: Setup GraalVM Environment
      uses: DeLaGuardo/setup-graalvm@2.0
      with:
        graalvm-version: $graalVersion
    - name: Setup SBT 
      run: java -version
